### ISSUE TITLE
remove support for python <= 3.5.3

### ISSUE THREAD

**Issue by trsa** [aio-libs/aioelasticsearch#155]
Since it is not supported since [aiohttp 3.0](https://aiohttp.readthedocs.io/en/stable/changes.html#id222) and the minimum supported version is going to be 3.5.0, unnecessary python <= 3.5.3  compatibility code should be removed

**Comment by hellysmile** [comment]
fixed by https://github.com/aio-libs/aioelasticsearch/pull/157
